name: actions/node-module-save-cache
description: "Install node_modules and save it to cache"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check cache for "node_modules"
      id: cache
      uses: martijnhols/actions-cache/check@v3
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Save "node_modules" to cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: martijnhols/actions-cache/save@v3
      with:
        path: "**/node_modules"
        key: ${{ steps.cache.outputs.primary-key }}
