name: actions/node-modules/restore
description: "Restore node_modules from cache"
inputs:
  cache-key:
    description: "Key to retrieve node_modules from cache"
    required: false
    default: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
runs:
  using: "composite"
  steps:
    - name: Restore "node_modules" from cache
      uses: actions/cache/restore@v4
      with:
        path: "**/node_modules"
        key: ${{ inputs.cache-key }}
