name: actions/node-module-save-cache
description: "Install node_modules and save it to cache"
inputs:
  install-command:
    description: "Command to run to install node_modules (yarn, npm, pnpm...)"
    required: true
    default: yarn install --frozen-lockfile
  cache-key:
    description: "Key to store node_modules in cache"
    required: true
    default: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
runs:
  using: "composite"
  steps:
    - name: Check cache for "node_modules"
      id: cache
      uses: martijnhols/actions-cache/check@v3
      with:
        path: "**/node_modules"
        key: ${{ inputs.cache-key }}

    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{ inputs.install-command }}

    - name: Save "node_modules" to cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: martijnhols/actions-cache/save@v3
      with:
        path: "**/node_modules"
        key: ${{ steps.cache.outputs.primary-key }}
