name: Restore node_modules from cache
description: "Check out repository and restore 'node_modules' from cache"
inputs:
  cache-key:
    description: "Key for node_modules cache"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Restore "node_modules" from cache
      uses: martijnhols/actions-cache/restore@v3
      with:
        path: "**/node_modules"
        key: ${{ inputs.cache-key }}
        # Fail when the cache could not be found (this should never happen unless you have a misconfiguration)
        required: true
