name: actions/node-module-restore-cache
description: "Restore node_modules from cache"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore "node_modules" from cache
      uses: martijnhols/actions-cache/restore@v3
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
