name: Run Nitro Test Node
description: 'Checks out the Nitro repository and runs the local test node setup'
inputs:
  token-bridge:
    required: false
    default: 'false'
    description: 'Whether the token bridge should be deployed on the test node'
runs:
  using: 'composite'
  steps:
    - name: Checkout OffchainLabs/nitro
      uses: actions/checkout@v3
      with:
        repository: OffchainLabs/nitro
        submodules: 'recursive'
        path: 'nitro'
        ref: 'v2.0.9'

    - name: Checkout OffchainLabs/arbitrum-sdk
      if: inputs.token-bridge == 'true'
      uses: actions/checkout@v3
      with:
        repository: OffchainLabs/arbitrum-sdk
        path: 'arbitrum-sdk'

    - name: Start background Nitro test-node.bash
      shell: bash
      # Currently, you can't run parallel steps, so we add the "&" to run this step in the background
      #
      # See https://stackoverflow.com/a/72203688 for more info
      run: |
        cd nitro
        ./test-node.bash --init --no-blockscout &

    - name: Wait for Nitro startup
      shell: bash
      run: ${{ github.action_path }}/waitForNitro.sh
