name: Run nitro-testnode
description: 'Checks out the nitro-testnode repository and runs the local testnode'
inputs:
  nitro-testnode-ref:
    required: false
    default: 'release'
    description: 'The nitro-testnode branch to use'
  nitro-contracts-branch:
    required: false
    description: 'The nitro-contracts branch to use'
  token-bridge-branch:
    required: false
    description: 'The token-bridge-contracts branch to use'
  args:
    required: false
    default: ''
    description: 'Additional args that can be supplied to the testnode script'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: OffchainLabs/nitro-testnode
        submodules: true
        path: 'nitro-testnode'
        ref: ${{ inputs.nitro-testnode-ref }}

    - name: Start background nitro-testnode test-node.bash
      shell: bash
      # Currently, you can't run parallel steps, so we add the "&" to run this step in the background
      #
      # See https://stackoverflow.com/a/72203688 for more info
      run: |
        cd nitro-testnode

        if [ -n "${{ inputs.nitro-contracts-branch }}" ]; then
          export NITRO_CONTRACTS_BRANCH="${{ inputs.nitro-contracts-branch }}"
        fi
        if [ -n "${{ inputs.token-bridge-branch }}" ]; then
          export TOKEN_BRIDGE_BRANCH="${{ inputs.token-bridge-branch }}"
        fi

        ./test-node.bash --init ${{ inputs.args }} &

    - name: Wait for L2 startup
      shell: bash
      run: ${{ github.action_path }}/waitForNitro.sh 8547

    - name: Wait for L3 startup
      if: ${{ contains(inputs.args, '--l3node') }}
      shell: bash
      run: ${{ github.action_path }}/waitForNitro.sh 3347

    - name: Wait for L2 token bridge deployment
      if: ${{ contains(inputs.args, '--tokenbridge') }}
      shell: bash
      run: ${{ github.action_path }}/waitForTokenBridge.sh localNetwork.json

    - name: Wait for L3 token bridge deployment
      if: ${{ contains(inputs.args, '--l3-token-bridge') }}
      shell: bash
      run: ${{ github.action_path }}/waitForTokenBridge.sh l2l3_network.json
