name: Run Nitro Test Node
description: 'Checks out the Nitro repository and runs the local test node setup'
inputs:
  no-token-bridge:
    required: false
    default: 'false'
    description: 'Whether to skip deploying the token bridge on the test node'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: OffchainLabs/nitro-testnode
        path: 'nitro-testnode'
        ref: 'release'

    - name: Start background nitro-testnode test-node.bash
      shell: bash
      # Currently, you can't run parallel steps, so we add the "&" to run this step in the background
      #
      # See https://stackoverflow.com/a/72203688 for more info
      run: |
        cd nitro-testnode
        ./test-node.bash --init ${{ inputs.no-token-bridge == 'true' && '--no-tokenbridge' || '' }} &

    - name: Wait for nitro startup
      shell: bash
      run: ${{ github.action_path }}/waitForNitro.sh
