name: Run Nitro Test Node
description: 'Checks out the Nitro repository and runs the local test node setup'
inputs:
  no-token-bridge:
    required: false
    default: 'false'
    description: 'Whether to skip deploying the token bridge on the test node'
  args:
    required: false
    default: ''
    description: 'Additional args that can be supplied to the test node script'
  nitro-testnode-ref:
    required: false
    default: 'release'
    description: 'The nitro-testnode branch to use'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: OffchainLabs/nitro-testnode
        submodules: true
        path: 'nitro-testnode'
        ref: ${{ inputs.nitro-testnode-ref }}

    - name: Echo commands
      shell: bash
      run: echo ${{ inputs.args }}

    - name: Start background nitro-testnode test-node.bash
      shell: bash
      # Currently, you can't run parallel steps, so we add the "&" to run this step in the background
      #
      # See https://stackoverflow.com/a/72203688 for more info
      run: |
        cd nitro-testnode
        ./test-node.bash --init ${{ inputs.no-token-bridge == 'true' && '--no-tokenbridge' || '' }} ${{ inputs.args }}

    - name: Wait for nitro startup
      shell: bash
      run: ${{ github.action_path }}/waitForNitro.sh

    - name: Wait for token bridge deployment
      if: ${{ inputs.no-token-bridge != 'true' }}
      shell: bash
      run: ${{ github.action_path }}/waitForTokenBridge.sh
