name: actions/run-nitro-test-node

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-with-defaults:
    name: 'Run with defaults'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node

  run-with-token-bridge:
    name: 'Run with token bridge deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node
        with:
          args: --tokenbridge

  run-with-l3:
    name: 'Run with L3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node
        with:
          args: --tokenbridge --l3node

  run-with-l3-with-token-bridge:
    name: 'Run with L3 with token bridge deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node
        with:
          args: --tokenbridge --l3node --l3-token-bridge

  run-with-no-simple:
    name: 'Run with --no-simple mode'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node
        with:
          args: --no-simple
