name: actions/run-nitro-test-node

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-with-defaults:
    name: 'Run with defaults'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: OffchainLabs/actions/run-nitro-test-node@look-for-networks
        with:
          nitro-testnode-ref: master

  run-with-token-bridge:
    name: 'Run without token bridge deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: OffchainLabs/actions/run-nitro-test-node@look-for-networks
        with:
          nitro-testnode-ref: master
          no-token-bridge: true

  run-with-args:
    name: 'Run with args'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: OffchainLabs/actions/run-nitro-test-node@look-for-networks
        with:
          nitro-testnode-ref: master
          args: --detach

  run-with-simple:
    name: 'Run without token bridge deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: OffchainLabs/actions/run-nitro-test-node@look-for-networks
        with:
          nitro-testnode-ref: master
          no-simple: false

