name: actions/run-nitro-test-node

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-with-defaults:
    name: "Run with defaults"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node

  run-with-token-bridge:
    name: "Run without token bridge deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node
        with:
          no-token-bridge: true

  run-with-args:
    name: "Run with args"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node
        with:
          args: --detach

  run-with-simple:
    name: "Run in simple mode"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-nitro-test-node
        with:
          no-simple: false
