name: Test OffchainLabs/actions/run-nitro-test-node

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: 'Test Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./run-nitro-test-node
